### ISSUE TITLE
(To loveemu, from GHB from smw central) May I submit petiteMM to smw central?

### ISSUE THREAD

**Issue by GhbSmwc** [loveemu/loveemu-lab#1]
Smwc users found this tool really helpful on porting music. I'm sad that not a single user from smwc ever ask you until I signed up here to ask for permission. Is that okay? Don't worry, if yes, I'll show your github page and your name. (By the way, this is the first time posting a message here). Here is my email: 16asy01@westottawa.net (in case I miss your answer).

**Comment by loveemu** [comment]
Please do. PetiteMM can be redistributed free.

PetiteMM is co-authored with gocha (maintainer of snes9x-rr, s/he has also made several custom SMW musics btw). So please put his/her name there too.

Thank you for using our tool! Please create a good tunes with it :)
