### ISSUE TITLE
vgmtrans only source code

### ISSUE THREAD

**Issue by GhbSmwc** [loveemu/loveemu-lab#3]
I notice a problem: there is no application or program file to drop the rom file in, not even a batch file. Here is the download page: https://github.com/vgmtrans/vgmtrans. And I cannot assemble it (my computer was attacked by the "sunkist.notifyicondata" (it shows up when you log off your computer or shutdown (bringing up the "end program" window)) malware until I deleted and also accidently delete most of the innocent files, thus making some program file throw a blank error message upon attempting to open them). Is the reason why they are in source code form is because of legal reason?

(I wish I can put all my issues in the same place)

**Comment by loveemu** [comment]
See release tab for compiled binary.
