### ISSUE TITLE
What are the system requirements?

### ISSUE THREAD

**Issue by GhbSmwc** [loveemu/loveemu-lab#4]
I'm testing the software, and found this issue upon running the software:

"VGMTrans.exe is not a valid win32 application"

I'm using windows xp, version 5.1.2600 (seen on the command prompt). I notice that my computer is missing some system requirements, what are they?

oh yeah, here is the link: https://github.com/vgmtrans/vgmtrans/releases/tag/interim-20150420

I clicked the link "vgmtrans-interim-20150420.7z".

**Comment by loveemu** [comment]
I am not sure but it probably requires Windows Vista or later.

Also, please do not post application-specific issues here. Use the application's issue tracker instead.
